openapi: 3.1.0
info:
  title: Owner Invoices
  version: '1.0'
  description: Owner api docs for propensi team
  contact:
    name: Charis
    email: charis@mamiteam.com
    url: 'https://mamikos.com'
servers:
  - url: 'http://jambu.kerupux.com'
    description: staging
paths:
  /oauth/owner/purchase-history:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/purchase-history-success'
        '401':
          $ref: '#/components/responses/purchase-history-failed'
        '422':
          $ref: '#/components/responses/purchase-history-failed'
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/purchase-history'
  '/oauth/owner/{id}/purchase-history':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: owner_id
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Invoice'
              examples:
                Response for a mamiads invoice:
                  value:
                    data:
                      invoice_number: MA1209
                      status: paid
                      type: mamiads
                      amount: 1000000
                      paid_amount: 9600000
                      paid_at: '2022-04-10T16:30:00+07:00Z'
                      expired_at: null
                Response for gp invoice:
                  value:
                    data:
                      invoice_number: GP/1878
                      status: unpaid
                      type: gp
                      amount: 500000
                      paid_amount: 5000000
                      paid_at: null
                      expired_at: null
                Response for expired invoice:
                  value:
                    data:
                      invoice_number: MA7654
                      status: expired
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: null
                      expired_at: '2022-04-10T10:30:00+07:00Z'
      operationId: get-oauth-owner-id-purchase-history
      description: Get Purchase History from certain owner
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}\:[0-9]{2}\:[0-9]{2}\+[0-9]{2}\:[0-9]{2}'
                  example: '2022-04-10T16:30:00+07:00Z'
                  description: 'must within Asia/Jakarta timezone (UTC +7) by default. Using ISO8601 format (YYYY-MM-DDTHH:mm:ssZ)'
                invoice_status:
                  type:
                    - string
                    - 'null'
                  enum:
                    - paid
                    - unpaid
                    - expired
                  description: Invoice payment status filter (optional)
                invoice_type:
                  type:
                    - string
                    - 'null'
                  enum:
                    - gp
                    - mamiads
                  description: 'invoice type filter (optional), will be gp, mamiads, or null'
                limit:
                  type:
                    - integer
                    - 'null'
                  description: Limit of the invoice per owner
              required:
                - date
            examples:
              Requesting 10 invoices from that date that have paid status regardless the type:
                value:
                  date: '2022-04-10T16:30:00+07:00Z'
                  invoice_status: paid
                  invoice_type: null
                  limit: 10
              Request all mamiads invoices regardless the status:
                value:
                  date: '2022-04-10T16:30:00+07:00Z'
                  invoice_status: null
                  invoice_type: mamiads
                  limit: null
        description: ''
components:
  schemas:
    Invoice:
      title: Invoice
      type: object
      description: Invoice model
      examples:
        - invoice_number: MA165
          status: paid
          type: mamiads
          amount: 100000
          paid_amount: 100000
          paid_at: '2022-04-10T10:30:00+07:00Z'
          expired_at: null
        - invoice_number: MA432
          status: unpaid
          type: mamiads
          amount: 100000
          paid_amount: 100000
          paid_at: null
          expired_at: null
        - invoice_number: MA896
          status: expired
          type: mamiads
          amount: 100000
          paid_amount: 100000
          paid_at: null
          expired_at: '2022-04-10T10:30:00+07:00Z'
        - invoice_number: GP/165
          status: paid
          type: gp
          amount: 100000
          paid_amount: 100000
          paid_at: '2022-04-10T10:30:00+07:00Z'
          expired_at: null
        - invoice_number: GP-165
          status: expired
          type: gp
          amount: 100000
          paid_amount: 100000
          paid_at: null
          expired_at: '2022-04-10T10:30:00+07:00Z'
        - invoice_number: GP/5732
          status: unpaid
          type: gp
          amount: 100000
          paid_amount: 100000
          paid_at: null
          expired_at: null
      properties:
        invoice_number:
          type: string
        status:
          type: string
          enum:
            - paid
            - unpaid
            - expired
          description: 'Status of payment, will be either paid, unpaid, or expired'
        type:
          type: string
          enum:
            - mamiads
            - gp
          description: 'type of invoice, for now will be either gp or mamiads'
        amount:
          type: number
          description: the charged amount
          example: 100000
        paid_amount:
          type: number
          description: amount paid by the owner. might diferent from amount field if there is admin fee/voucher/other discount
          example: 200000
        paid_at:
          type:
            - string
            - 'null'
          description: 'Will be within Asia/Jakarta timezone (UTC +7) by default. Using ISO8601 format (YYYY-MM-DDTHH:mm:ssZ), only filled when transaction is paid'
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}\:[0-9]{2}\:[0-9]{2}\+[0-9]{2}\:[0-9]{2}Z'
          example: '2022-04-10T10:30:00+07:00Z'
        expired_at:
          type:
            - string
            - 'null'
          description: 'Will be within Asia/Jakarta timezone (UTC +7) by default. Using ISO8601 format (YYYY-MM-DDTHH:mm:ssZ), only filled when transaction is expired'
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}\:[0-9]{2}\:[0-9]{2}\+[0-9]{2}\:[0-9]{2}'
          example: '2022-04-10T10:30:00+07:00Z'
  requestBodies:
    purchase-history:
      content:
        application/json:
          schema:
            type: object
            properties:
              owner_id:
                type: array
                uniqueItems: true
                description: array of owner id to be processed
                items:
                  type: integer
                  minimum: 1
                  maximum: 20
              date:
                type: string
                pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}\:[0-9]{2}\:[0-9]{2}\+[0-9]{2}\:[0-9]{2}'
                example: '2022-04-10T10:30:00+07:00Z'
                description: 'must within Asia/Jakarta timezone (UTC +7) by default. Using ISO8601 format (YYYY-MM-DDTHH:mm:ssZ)'
              invoice_status:
                type:
                  - string
                  - 'null'
                description: 'status filter for the invoices, either paid, unpaid, or expired'
                enum:
                  - paid
                  - unpaid
                  - expired
              invoice_type:
                type:
                  - string
                  - 'null'
                enum:
                  - gp
                  - mamiads
                description: invoice type filter
              limit:
                type:
                  - integer
                  - 'null'
            required:
              - owner_id
              - date
          examples:
            example-10-maksimum-invoice-per-owner-id:
              value:
                owner_id:
                  - 1
                  - 3
                  - 5
                date: '2022-04-08T16:30:20+07:00Z'
                limit: 10
            example-without-limiting-invoices-per-owner-id:
              value:
                owner_id:
                  - 1
                  - 2
                  - 3
                  - 4
                date: '2022-04-08T16:30:20+07:00Z'
                limit: null
      description: 'Purchase History request body, date field must within Asia/Jakarta timezone (UTC +7) by default and using ISO8601 format'
  responses:
    purchase-history-success:
      description: Purchase history response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  '{owner_id}':
                    type: array
                    items:
                      $ref: '#/components/schemas/Invoice'
          examples:
            Response for multiple user case:
              value:
                data:
                  '1':
                    - invoice_number: string
                      status: paid
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: '2022-04-10T10:30:00+07:00Z'
                      expired_at: null
                    - invoice_number: string
                      status: unpaid
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: null
                      expired_at: null
                    - invoice_number: string
                      status: expired
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: null
                      expired_at: '2022-04-10T10:30:00+07:00Z'
                  '3':
                    - invoice_number: string
                      status: paid
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: '2022-04-10T10:30:00+07:00Z'
                      expired_at: null
                    - invoice_number: string
                      status: unpaid
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: null
                      expired_at: null
                    - invoice_number: string
                      status: expired
                      type: mamiads
                      amount: 100000
                      paid_amount: 200000
                      paid_at: null
                      expired_at: '2022-04-10T10:30:00+07:00Z'
      headers: {}
    purchase-history-failed:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
  securitySchemes:
    machine-act:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
